/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

// Possible values are - \"VERIFIED\" - \"UE_DNN_NOT_VERIFIED\" - \"NW_DNN_NOT_VERIFIED\" 
type DnnSelectionMode struct {
}
