/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient
import (
	"os"
)

type InlineResponse201 struct {
	JsonData SmContextCreatedData `json:"jsonData,omitempty" xml:"jsonData"`
	BinaryDataN2SmInformation *os.File `json:"binaryDataN2SmInformation,omitempty" xml:"binaryDataN2SmInformation"`
}
