/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type EpsPdnCnxInfo struct {
	PgwS8cFteid string `json:"pgwS8cFteid" xml:"pgwS8cFteid"`
	PgwNodeName string `json:"pgwNodeName,omitempty" xml:"pgwNodeName"`
}
