/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient
import (
	"os"
)

type Body3 struct {
	JsonData HsmfUpdateData `json:"jsonData,omitempty" xml:"jsonData"`
	BinaryDataN1SmInfoFromUe *os.File `json:"binaryDataN1SmInfoFromUe,omitempty" xml:"binaryDataN1SmInfoFromUe"`
	BinaryDataUnknownN1SmInfo *os.File `json:"binaryDataUnknownN1SmInfo,omitempty" xml:"binaryDataUnknownN1SmInfo"`
}
