/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type SmContextCreatedData struct {
	PduSessionId int32 `json:"pduSessionId,omitempty" xml:"pduSessionId"`
	SNssai Snssai `json:"sNssai,omitempty" xml:"sNssai"`
	UpCnxState UpCnxState `json:"upCnxState,omitempty" xml:"upCnxState"`
	N2SmInfo RefToBinaryData `json:"n2SmInfo,omitempty" xml:"n2SmInfo"`
	N2SmInfoType int32 `json:"n2SmInfoType,omitempty" xml:"n2SmInfoType"`
	AllocatedEbiList []EbiArpMapping `json:"allocatedEbiList,omitempty" xml:"allocatedEbiList"`
	HoState HoState `json:"hoState,omitempty" xml:"hoState"`
	SupportedFeatures string `json:"supportedFeatures,omitempty" xml:"supportedFeatures"`
}
