/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type Dynamic5qi struct {
	PriorityLevel int32 `json:"priorityLevel" xml:"priorityLevel"`
	PacketDelBudget int32 `json:"packetDelBudget" xml:"packetDelBudget"`
	PacketErrRate int32 `json:"packetErrRate" xml:"packetErrRate"`
	DelayCritical DelayCritical `json:"delayCritical,omitempty" xml:"delayCritical"`
	AverWindow string `json:"averWindow,omitempty" xml:"averWindow"`
	MaxDataBurstVol int32 `json:"maxDataBurstVol,omitempty" xml:"maxDataBurstVol"`
}
