/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

// Possible values are - \"QOS_FULFILLED\" - \"QOS_NOT_FULFILLED\" - \"UP_SEC_FULFILLED\" - \"UP_SEC_NOT_FULFILLED\" 
type NotificationCause struct {
}
