/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type Snssai struct {
	Sst int32 `json:"sst" xml:"sst"`
	Sd string `json:"sd,omitempty" xml:"sd"`
}
