/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type Guami struct {
	PlmnId PlmnId `json:"plmnId" xml:"plmnId"`
	AmfId string `json:"amfId" xml:"amfId"`
}
