/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient
import (
	"os"
)

type InlineResponse4003 struct {
	JsonData HsmfUpdateError `json:"jsonData,omitempty" xml:"jsonData"`
	BinaryDataN1SmInfoToUe *os.File `json:"binaryDataN1SmInfoToUe,omitempty" xml:"binaryDataN1SmInfoToUe"`
}
