/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type QosFlowProfile struct {
	Var5qi int32 `json:"5qi,omitempty" xml:"5qi"`
	NonDynamic5qi NonDynamic5qi `json:"nonDynamic5qi,omitempty" xml:"nonDynamic5qi"`
	Dynamic5qi Dynamic5qi `json:"dynamic5qi,omitempty" xml:"dynamic5qi"`
	Arp Arp `json:"arp,omitempty" xml:"arp"`
	GbrQosFlowInfo GbrQosFlowInformation `json:"gbrQosFlowInfo,omitempty" xml:"gbrQosFlowInfo"`
	Rqa ReflectiveQosAttribute `json:"rqa,omitempty" xml:"rqa"`
}
