/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

// Possible values are - \"REL_DUE_TO_HO\" - \"EPS_FALLBACK\" - \"REL_DUE_TO_UP_SEC\" - \"DNN_CONGESTION\" - \"S-NSSAI_CONGESTION\" - \"REL_DUE_TO_REACTIVATION\" 
type Cause struct {
}
