/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type Arp struct {
	PriorityLevel int32 `json:"priorityLevel" xml:"priorityLevel"`
	PreemptCap PreemptionCapability `json:"preemptCap" xml:"preemptCap"`
	PreemptVuln PreemptionVulnerability `json:"preemptVuln" xml:"preemptVuln"`
}
