/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient
import (
	"time"
)

type PduSessionCreateData struct {
	Supi string `json:"supi,omitempty" xml:"supi"`
	UnauthenticatedSupi bool `json:"unauthenticatedSupi,omitempty" xml:"unauthenticatedSupi"`
	Pei string `json:"pei,omitempty" xml:"pei"`
	PduSessionId int32 `json:"pduSessionId,omitempty" xml:"pduSessionId"`
	Dnn string `json:"dnn" xml:"dnn"`
	SNssai Snssai `json:"sNssai,omitempty" xml:"sNssai"`
	VsmfId string `json:"vsmfId" xml:"vsmfId"`
	RequestType RequestType `json:"requestType,omitempty" xml:"requestType"`
	EpsBearerId []int32 `json:"epsBearerId,omitempty" xml:"epsBearerId"`
	PgwS8cFteid string `json:"pgwS8cFteid,omitempty" xml:"pgwS8cFteid"`
	VsmfPduSessionUri string `json:"vsmfPduSessionUri" xml:"vsmfPduSessionUri"`
	VcnTunnelInfo TunnelInfo `json:"vcnTunnelInfo" xml:"vcnTunnelInfo"`
	AnType AccessType `json:"anType" xml:"anType"`
	UeLocation UserLocation `json:"ueLocation,omitempty" xml:"ueLocation"`
	UeTimeZone string `json:"ueTimeZone,omitempty" xml:"ueTimeZone"`
	AddUeLocation UserLocation `json:"addUeLocation,omitempty" xml:"addUeLocation"`
	AddUeLocTime time.Time `json:"addUeLocTime,omitempty" xml:"addUeLocTime"`
	Gpsi string `json:"gpsi,omitempty" xml:"gpsi"`
	N1SmInfoFromUe RefToBinaryData `json:"n1SmInfoFromUe,omitempty" xml:"n1SmInfoFromUe"`
	UnknownN1SmInfo RefToBinaryData `json:"unknownN1SmInfo,omitempty" xml:"unknownN1SmInfo"`
	SupportedFeatures string `json:"supportedFeatures,omitempty" xml:"supportedFeatures"`
	HPcfId string `json:"hPcfId,omitempty" xml:"hPcfId"`
	HoPreparationIndication bool `json:"hoPreparationIndication,omitempty" xml:"hoPreparationIndication"`
	SelMode DnnSelectionMode `json:"selMode,omitempty" xml:"selMode"`
}
