/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type SmContextUpdatedData struct {
	UpCnxState UpCnxState `json:"upCnxState,omitempty" xml:"upCnxState"`
	HoState HoState `json:"hoState,omitempty" xml:"hoState"`
	ReleaseEbiList []int32 `json:"releaseEbiList,omitempty" xml:"releaseEbiList"`
	AllocatedEbiList []EbiArpMapping `json:"allocatedEbiList,omitempty" xml:"allocatedEbiList"`
	ModifiedEbiList []EbiArpMapping `json:"modifiedEbiList,omitempty" xml:"modifiedEbiList"`
	N1SmMsg RefToBinaryData `json:"n1SmMsg,omitempty" xml:"n1SmMsg"`
	N2SmInfo RefToBinaryData `json:"n2SmInfo,omitempty" xml:"n2SmInfo"`
	N2SmInfoType int32 `json:"n2SmInfoType,omitempty" xml:"n2SmInfoType"`
	EpsBearerSetup []string `json:"epsBearerSetup,omitempty" xml:"epsBearerSetup"`
	DataForwarding bool `json:"dataForwarding,omitempty" xml:"dataForwarding"`
}
