/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type VsmfUpdateData struct {
	RequestIndication RequestIndication `json:"requestIndication" xml:"requestIndication"`
	SessionAmbr Ambr `json:"sessionAmbr,omitempty" xml:"sessionAmbr"`
	QosFlowsAddModRequestList []QosFlowAddModifyRequestItem `json:"qosFlowsAddModRequestList,omitempty" xml:"qosFlowsAddModRequestList"`
	QosFlowsRelRequestList []QosFlowReleaseRequestItem `json:"qosFlowsRelRequestList,omitempty" xml:"qosFlowsRelRequestList"`
	EpsBearerInfo []EpsBearerInfo `json:"epsBearerInfo,omitempty" xml:"epsBearerInfo"`
	RevokeEbiList []int32 `json:"revokeEbiList,omitempty" xml:"revokeEbiList"`
	ModifiedEbiList []EbiArpMapping `json:"modifiedEbiList,omitempty" xml:"modifiedEbiList"`
	Pti int32 `json:"pti,omitempty" xml:"pti"`
	N1SmInfoToUe RefToBinaryData `json:"n1SmInfoToUe,omitempty" xml:"n1SmInfoToUe"`
	Cause Cause `json:"cause,omitempty" xml:"cause"`
}
