/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient
import (
	"time"
)

type HsmfUpdateData struct {
	RequestIndication RequestIndication `json:"requestIndication" xml:"requestIndication"`
	Pei string `json:"pei,omitempty" xml:"pei"`
	VcnTunnelInfo TunnelInfo `json:"vcnTunnelInfo,omitempty" xml:"vcnTunnelInfo"`
	AnType AccessType `json:"anType,omitempty" xml:"anType"`
	UeLocation UserLocation `json:"ueLocation,omitempty" xml:"ueLocation"`
	UeTimeZone string `json:"ueTimeZone,omitempty" xml:"ueTimeZone"`
	AddUeLocation UserLocation `json:"addUeLocation,omitempty" xml:"addUeLocation"`
	AddUeLocTime time.Time `json:"addUeLocTime,omitempty" xml:"addUeLocTime"`
	PauseCharging bool `json:"pauseCharging,omitempty" xml:"pauseCharging"`
	Pti int32 `json:"pti,omitempty" xml:"pti"`
	N1SmInfoFromUe RefToBinaryData `json:"n1SmInfoFromUe,omitempty" xml:"n1SmInfoFromUe"`
	UnknownN1SmInfo RefToBinaryData `json:"unknownN1SmInfo,omitempty" xml:"unknownN1SmInfo"`
	QosFlowsRelNotifyList []QosFlowItem `json:"qosFlowsRelNotifyList,omitempty" xml:"qosFlowsRelNotifyList"`
	QosFlowsNotifyList []QosFlowNotifyItem `json:"qosFlowsNotifyList,omitempty" xml:"qosFlowsNotifyList"`
	NotifyList []PduSessionNotifyItem `json:"NotifyList,omitempty" xml:"NotifyList"`
	EpsBearerId []int32 `json:"epsBearerId,omitempty" xml:"epsBearerId"`
	HoPreparationIndication bool `json:"hoPreparationIndication,omitempty" xml:"hoPreparationIndication"`
	RevokeEbiList []int32 `json:"revokeEbiList,omitempty" xml:"revokeEbiList"`
	Cause Cause `json:"cause,omitempty" xml:"cause"`
}
