/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient
import (
	"time"
)

type VsmfUpdatedData struct {
	QosFlowsAddModList []QosFlowItem `json:"qosFlowsAddModList,omitempty" xml:"qosFlowsAddModList"`
	QosFlowsRelList []QosFlowItem `json:"qosFlowsRelList,omitempty" xml:"qosFlowsRelList"`
	QosFlowsFailedtoAddModList []QosFlowItem `json:"qosFlowsFailedtoAddModList,omitempty" xml:"qosFlowsFailedtoAddModList"`
	QosFlowsFailedtoRelList []QosFlowItem `json:"qosFlowsFailedtoRelList,omitempty" xml:"qosFlowsFailedtoRelList"`
	N1SmInfoFromUe RefToBinaryData `json:"n1SmInfoFromUe,omitempty" xml:"n1SmInfoFromUe"`
	UnknownN1SmInfo RefToBinaryData `json:"unknownN1SmInfo,omitempty" xml:"unknownN1SmInfo"`
	UeLocation UserLocation `json:"ueLocation,omitempty" xml:"ueLocation"`
	UeTimeZone string `json:"ueTimeZone,omitempty" xml:"ueTimeZone"`
	AddUeLocation UserLocation `json:"addUeLocation,omitempty" xml:"addUeLocation"`
	AddUeLocTime time.Time `json:"addUeLocTime,omitempty" xml:"addUeLocTime"`
}
