/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type GbrQosFlowInformation struct {
	MaxFbrDl string `json:"maxFbrDl" xml:"maxFbrDl"`
	MaxFbrUl string `json:"maxFbrUl" xml:"maxFbrUl"`
	GuaFbrDl string `json:"guaFbrDl" xml:"guaFbrDl"`
	GuaFbrUl string `json:"guaFbrUl" xml:"guaFbrUl"`
	NotifControl NotificationControl `json:"notifControl,omitempty" xml:"notifControl"`
	MaxPacketLossRateDl int32 `json:"maxPacketLossRateDl,omitempty" xml:"maxPacketLossRateDl"`
	MaxPacketLossRateUl int32 `json:"maxPacketLossRateUl,omitempty" xml:"maxPacketLossRateUl"`
}
