/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type SmContextUpdateError struct {
	Error ProblemDetails `json:"error" xml:"error"`
	N1SmMsg RefToBinaryData `json:"n1SmMsg,omitempty" xml:"n1SmMsg"`
	N2SmInfo RefToBinaryData `json:"n2SmInfo,omitempty" xml:"n2SmInfo"`
	N2SmInfoType int32 `json:"n2SmInfoType,omitempty" xml:"n2SmInfoType"`
	UpCnxState UpCnxState `json:"upCnxState,omitempty" xml:"upCnxState"`
}
