/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type Ambr struct {
	Uplink string `json:"uplink" xml:"uplink"`
	Downlink string `json:"downlink" xml:"downlink"`
}
