/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type PduSessionCreatedData struct {
	PduSessionType PduSessionType `json:"pduSessionType" xml:"pduSessionType"`
	SscMode string `json:"sscMode" xml:"sscMode"`
	HcnTunnelInfo TunnelInfo `json:"hcnTunnelInfo" xml:"hcnTunnelInfo"`
	SessionAmbr Ambr `json:"sessionAmbr" xml:"sessionAmbr"`
	QosFlowsSetupList []QosFlowSetupItem `json:"qosFlowsSetupList" xml:"qosFlowsSetupList"`
	PduSessionId int32 `json:"pduSessionId,omitempty" xml:"pduSessionId"`
	SNssai Snssai `json:"sNssai,omitempty" xml:"sNssai"`
	EnablePauseCharging bool `json:"enablePauseCharging,omitempty" xml:"enablePauseCharging"`
	UeIpv4Address string `json:"ueIpv4Address,omitempty" xml:"ueIpv4Address"`
	UeIpv6Prefix string `json:"ueIpv6Prefix,omitempty" xml:"ueIpv6Prefix"`
	N1SmInfoToUe RefToBinaryData `json:"n1SmInfoToUe,omitempty" xml:"n1SmInfoToUe"`
	EpsPdnCnxInfo EpsPdnCnxInfo `json:"epsPdnCnxInfo,omitempty" xml:"epsPdnCnxInfo"`
	EpsBearerInfo []EpsBearerInfo `json:"epsBearerInfo,omitempty" xml:"epsBearerInfo"`
	SupportedFeatures string `json:"supportedFeatures,omitempty" xml:"supportedFeatures"`
	UpSecurity UpSecurity `json:"upSecurity,omitempty" xml:"upSecurity"`
}
