/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

type QosFlowNotifyItem struct {
	Qfi int32 `json:"qfi" xml:"qfi"`
	NotificationCause NotificationCause `json:"notificationCause" xml:"notificationCause"`
}
