/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

import (
	"net/http"

	//"github.com/jerryduren/myactorproject/unc/smf"

	//"github.com/jerryduren/myactorproject/unc/smf"
)

// PostSmContexts - Create SM Context
func PostSmContexts(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)


	//smf.CreateSmContext(w, r)
}
