/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

type PduSessionCreateError struct {

	Error *ProblemDetails `json:"error"`

	N1smCause string `json:"n1smCause,omitempty"`

	N1SmInfoToUe *RefToBinaryData `json:"n1SmInfoToUe,omitempty"`
}
