/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

// RequestIndication - Possible values are - \"UE_REQ_PDU_SES_MOD\" - \"UE_REQ_PDU_SES_REL\" - \"PDU_SES_MOB\" - \"NW_REQ_PDU_SES_AUTH\" - \"NW_REQ_PDU_SES_MOD\" - \"NW_REQ_PDU_SES_REL\" 
type RequestIndication struct {
}
