/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

type Arp struct {

	PriorityLevel int32 `json:"priorityLevel"`

	PreemptCap *PreemptionCapability `json:"preemptCap"`

	PreemptVuln *PreemptionVulnerability `json:"preemptVuln"`
}
