/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

type EutraLocation struct {

	Tai *Tai `json:"tai"`

	Ecgi *Ecgi `json:"ecgi"`
}
