/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

import (
	"os"
)

type Body3 struct {

	JsonData *HsmfUpdateData `json:"jsonData,omitempty"`

	BinaryDataN1SmInfoFromUe **os.File `json:"binaryDataN1SmInfoFromUe,omitempty"`

	BinaryDataUnknownN1SmInfo **os.File `json:"binaryDataUnknownN1SmInfo,omitempty"`
}
