/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

type Dynamic5qi struct {

	PriorityLevel int32 `json:"priorityLevel"`

	PacketDelBudget int32 `json:"packetDelBudget"`

	PacketErrRate int32 `json:"packetErrRate"`

	DelayCritical *DelayCritical `json:"delayCritical,omitempty"`

	AverWindow string `json:"averWindow,omitempty"`

	MaxDataBurstVol int32 `json:"maxDataBurstVol,omitempty"`
}
