/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

import (
	"os"
)

type InlineResponse2011 struct {

	JsonData *PduSessionCreatedData `json:"jsonData,omitempty"`

	BinaryDataN1SmInfoToUe **os.File `json:"binaryDataN1SmInfoToUe,omitempty"`
}
