/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

import (
	"time"
)

type SmContextUpdateData struct {

	Pei string `json:"pei,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`

	ServingNfId string `json:"servingNfId,omitempty"`

	Guami *Guami `json:"guami,omitempty"`

	BackupAmfInfo []BackupAmfInfo `json:"backupAmfInfo,omitempty"`

	AnType *AccessType `json:"anType,omitempty"`

	PresenceInLadn bool `json:"presenceInLadn,omitempty"`

	UeLocation *UserLocation `json:"ueLocation,omitempty"`

	UeTimeZone string `json:"ueTimeZone,omitempty"`

	AddUeLocation *UserLocation `json:"addUeLocation,omitempty"`

	AddUeLocTime time.Time `json:"addUeLocTime,omitempty"`

	UpCnxState *UpCnxState `json:"upCnxState,omitempty"`

	HoState *HoState `json:"hoState,omitempty"`

	ToBeSwitched bool `json:"toBeSwitched,omitempty"`

	N1SmMsg *RefToBinaryData `json:"n1SmMsg,omitempty"`

	N2SmInfo *RefToBinaryData `json:"n2SmInfo,omitempty"`

	N2SmInfoType int32 `json:"n2SmInfoType,omitempty"`

	TargetServingNfId string `json:"targetServingNfId,omitempty"`

	SmContextStatusUri string `json:"smContextStatusUri,omitempty"`

	DataForwarding bool `json:"dataForwarding,omitempty"`

	EpsBearerSetup []string `json:"epsBearerSetup,omitempty"`

	RevokeEbiList []int32 `json:"revokeEbiList,omitempty"`

	Release bool `json:"release,omitempty"`

	Cause *Cause `json:"cause,omitempty"`
}
