/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

type SmContextUpdateError struct {

	Error *ProblemDetails `json:"error"`

	N1SmMsg *RefToBinaryData `json:"n1SmMsg,omitempty"`

	N2SmInfo *RefToBinaryData `json:"n2SmInfo,omitempty"`

	N2SmInfoType int32 `json:"n2SmInfoType,omitempty"`

	UpCnxState *UpCnxState `json:"upCnxState,omitempty"`
}
