/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

type StatusInfo struct {

	ResourceStatus *ResourceStatus `json:"resourceStatus"`

	Cause *Cause `json:"cause,omitempty"`
}
