/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smfapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

func Root(w http.ResponseWriter,r *http.Request){
	fmt.Fprintf(w, "Please set corroect base path, such as /nsmf-pduseesion/v1!")
}

var routes = Routes{
	{
		"Root",
		"GET",
		"/",
		Root,
	},

	{
		"Index",
		"GET",
		"/nsmf-pdusession/v1/",
		Index,
	},

	{
		"ReleasePduSession",
		strings.ToUpper("Post"),
		"/nsmf-pdusession/v1/pdu-sessions/{pduSessionRef}/release",
		ReleasePduSession,
	},

	{
		"UpdatePduSession",
		strings.ToUpper("Post"),
		"/nsmf-pdusession/v1/pdu-sessions/{pduSessionRef}/modify",
		UpdatePduSession,
	},

	{
		"ReleaseSmContext",
		strings.ToUpper("Post"),
		"/nsmf-pdusession/v1/sm-contexts/{smContextRef}/release",
		ReleaseSmContext,
	},

	{
		"RetrieveSmContext",
		strings.ToUpper("Post"),
		"/nsmf-pdusession/v1/sm-contexts/{smContextRef}/retrieve",
		RetrieveSmContext,
	},

	{
		"UpdateSmContext",
		strings.ToUpper("Post"),
		"/nsmf-pdusession/v1/sm-contexts/{smContextRef}/modify",
		UpdateSmContext,
	},

	{
		"PostPduSessions",
		strings.ToUpper("Post"),
		"/nsmf-pdusession/v1/pdu-sessions",
		PostPduSessions,
	},

	{
		"PostSmContexts",
		strings.ToUpper("Post"),
		"/nsmf-pdusession/v1/sm-contexts",
		PostSmContexts,
	},
}
