/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package 5gccommon

type UserLocation struct {

	EutraLocation *EutraLocation `json:"eutraLocation,omitempty"`

	NrLocation *NrLocation `json:"nrLocation,omitempty"`

	N3gaLocation *N3gaLocation `json:"n3gaLocation,omitempty"`
}
