/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package 5gccommon

type AccessType string

// List of AccessType
const (
	_3_GPP_ACCESS AccessType = "3GPP_ACCESS"
	NON_3_GPP_ACCESS AccessType = "NON_3GPP_ACCESS"
)
