/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package 5gccommon

type Ambr struct {

	Uplink string `json:"uplink"`

	Downlink string `json:"downlink"`
}
