/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smf

// HoState - Possible values are - \"NONE\" - \"PREPARING\" - \"PREPARED\" - \"COMPLETED\" - \"CANCELLED\" 
type HoState struct {
}
