/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PatchItem struct {

	Op *PatchOperation `json:"op"`

	Path string `json:"path"`

	From string `json:"from,omitempty"`

	Value *map[string]interface{} `json:"value,omitempty"`
}
