/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smf

type VsmfUpdateError struct {

	Error *ProblemDetails `json:"error"`

	Pti int32 `json:"pti,omitempty"`

	N1smCause string `json:"n1smCause,omitempty"`

	N1SmInfoFromUe *RefToBinaryData `json:"n1SmInfoFromUe,omitempty"`

	UnknownN1SmInfo *RefToBinaryData `json:"unknownN1SmInfo,omitempty"`
}
