/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smf

import (
	"time"
)

type SmContextCreateData struct {

	Supi string `json:"supi,omitempty"`

	UnauthenticatedSupi bool `json:"unauthenticatedSupi,omitempty"`

	Pei string `json:"pei,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`

	PduSessionId int32 `json:"pduSessionId,omitempty"`

	Dnn string `json:"dnn,omitempty"`

	SNssai *Snssai `json:"sNssai,omitempty"`

	HplmnSnssai *Snssai `json:"hplmnSnssai,omitempty"`

	ServingNfId string `json:"servingNfId"`

	Guami *Guami `json:"guami,omitempty"`

	RequestType *RequestType `json:"requestType,omitempty"`

	N1SmMsg *RefToBinaryData `json:"n1SmMsg,omitempty"`

	AnType *AccessType `json:"anType"`

	PresenceInLadn bool `json:"presenceInLadn,omitempty"`

	UeLocation *UserLocation `json:"ueLocation,omitempty"`

	UeTimeZone string `json:"ueTimeZone,omitempty"`

	AddUeLocation *UserLocation `json:"addUeLocation,omitempty"`

	AddUeLocTime time.Time `json:"addUeLocTime,omitempty"`

	SmContextStatusUri string `json:"smContextStatusUri"`

	HSmfUri string `json:"hSmfUri,omitempty"`

	AdditionalHsmfUri []string `json:"additionalHsmfUri,omitempty"`

	OldPduSessionId int32 `json:"oldPduSessionId,omitempty"`

	PduSessionsActivateList []int32 `json:"pduSessionsActivateList,omitempty"`

	UeEpsPdnConnection string `json:"ueEpsPdnConnection,omitempty"`

	HoState *HoState `json:"hoState,omitempty"`

	PcfId string `json:"pcfId,omitempty"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`

	SelMode *DnnSelectionMode `json:"selMode,omitempty"`

	BackupAmfInfo []BackupAmfInfo `json:"backupAmfInfo,omitempty"`
}
