/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smf

type UserLocation struct {

	EutraLocation *EutraLocation `json:"eutraLocation,omitempty"`

	NrLocation *NrLocation `json:"nrLocation,omitempty"`

	N3gaLocation *N3gaLocation `json:"n3gaLocation,omitempty"`
}
