/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NetworkId struct {

	Mnc string `json:"mnc,omitempty"`

	Mcc string `json:"mcc,omitempty"`
}
