/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smf

type EpsBearerInfo struct {

	Ebi int32 `json:"ebi"`

	PgwS8uFteid string `json:"pgwS8uFteid"`

	BearerLevelQoS string `json:"bearerLevelQoS"`
}
