/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smf

// DnnSelectionMode - Possible values are - \"VERIFIED\" - \"UE_DNN_NOT_VERIFIED\" - \"NW_DNN_NOT_VERIFIED\" 
type DnnSelectionMode struct {
}
