/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smf

type VsmfUpdateData struct {

	RequestIndication *RequestIndication `json:"requestIndication"`

	SessionAmbr *Ambr `json:"sessionAmbr,omitempty"`

	QosFlowsAddModRequestList []QosFlowAddModifyRequestItem `json:"qosFlowsAddModRequestList,omitempty"`

	QosFlowsRelRequestList []QosFlowReleaseRequestItem `json:"qosFlowsRelRequestList,omitempty"`

	EpsBearerInfo []EpsBearerInfo `json:"epsBearerInfo,omitempty"`

	RevokeEbiList []int32 `json:"revokeEbiList,omitempty"`

	ModifiedEbiList []EbiArpMapping `json:"modifiedEbiList,omitempty"`

	Pti int32 `json:"pti,omitempty"`

	N1SmInfoToUe *RefToBinaryData `json:"n1SmInfoToUe,omitempty"`

	Cause *Cause `json:"cause,omitempty"`
}
