/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smf

import (
	"time"
)

type VsmfUpdatedData struct {

	QosFlowsAddModList []QosFlowItem `json:"qosFlowsAddModList,omitempty"`

	QosFlowsRelList []QosFlowItem `json:"qosFlowsRelList,omitempty"`

	QosFlowsFailedtoAddModList []QosFlowItem `json:"qosFlowsFailedtoAddModList,omitempty"`

	QosFlowsFailedtoRelList []QosFlowItem `json:"qosFlowsFailedtoRelList,omitempty"`

	N1SmInfoFromUe *RefToBinaryData `json:"n1SmInfoFromUe,omitempty"`

	UnknownN1SmInfo *RefToBinaryData `json:"unknownN1SmInfo,omitempty"`

	UeLocation *UserLocation `json:"ueLocation,omitempty"`

	UeTimeZone string `json:"ueTimeZone,omitempty"`

	AddUeLocation *UserLocation `json:"addUeLocation,omitempty"`

	AddUeLocTime time.Time `json:"addUeLocTime,omitempty"`
}
