/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smf

type Guami struct {

	PlmnId *PlmnId `json:"plmnId"`

	AmfId string `json:"amfId"`
}
