/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smf

// RequestType - Possible values are - \"INITIAL_REQUEST\" - \"EXISTING_PDU_SESSION\" - \"INITIAL_EMERGENCY_REQUEST\" - \"EXISTING_EMERGENCY_PDU_SESSION\" 
type RequestType struct {
}
