/*
 * Common Data Types
 *
 * Common Data Types
 *
 * API version: 1.R15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package 5gccommon

type Tai struct {

	PlmnId *PlmnId `json:"plmnId"`

	Tac string `json:"tac"`
}
