/*
 * SMF PDU Session
 *
 * SMF PDU Session Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"github.com/jerryduren/myactorproject/unc/smf/smfapi"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//  sw "github.com/myname/myrepo/go"
	//
)

func main() {
	log.Printf("Server started")

	router := smfapi.NewRouter()

	log.Fatal(http.ListenAndServe("0.0.0.0:8080", router))
}
