/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SmfRegistration struct {

	SmfId string `json:"smfId"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`

	PduSessionId int32 `json:"pduSessionId"`

	Dnn string `json:"dnn"`

	PcscfRestorationCallbackUri string `json:"pcscfRestorationCallbackUri,omitempty"`
}
