/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AmfNon3GppAccessRegistrationModification struct {

	PurgeFlag bool `json:"purgeFlag,omitempty"`

	Pei string `json:"pei,omitempty"`
}
