/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.PreR15.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"//demohost.com/nudm-uecm/v1/",
		Index,
	},

	{
		"Get",
		strings.ToUpper("Get"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/amf-3gpp-access",
		Get,
	},

	{
		"Get",
		strings.ToUpper("Get"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/amf-non-3gpp-access",
		Get,
	},

	{
		"Registration",
		strings.ToUpper("Put"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/amf-3gpp-access",
		Registration,
	},

	{
		"Register",
		strings.ToUpper("Put"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/amf-non-3gpp-access",
		Register,
	},

	{
		"Update",
		strings.ToUpper("Patch"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/amf-3gpp-access",
		Update,
	},

	{
		"Update",
		strings.ToUpper("Patch"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/amf-non-3gpp-access",
		Update,
	},

	{
		"Deregistration",
		strings.ToUpper("Delete"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/smf-registrations/{pduSessionId}",
		Deregistration,
	},

	{
		"Registration",
		strings.ToUpper("Put"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/smf-registrations/{pduSessionId}",
		Registration,
	},

	{
		"Get",
		strings.ToUpper("Get"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/smsf-3gpp-access",
		Get,
	},

	{
		"Deregistration",
		strings.ToUpper("Delete"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/smsf-3gpp-access",
		Deregistration,
	},

	{
		"Deregistration",
		strings.ToUpper("Delete"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/smsf-non-3gpp-access",
		Deregistration,
	},

	{
		"Get",
		strings.ToUpper("Get"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/smsf-non-3gpp-access",
		Get,
	},

	{
		"UpdateSMSFReg3GPP",
		strings.ToUpper("Put"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/smsf-3gpp-access",
		UpdateSMSFReg3GPP,
	},

	{
		"Registration",
		strings.ToUpper("Put"),
		"//demohost.com/nudm-uecm/v1/{ueId}/registrations/smsf-non-3gpp-access",
		Registration,
	},
}
